version: 3

dotenv:
  - .env
  - .env.local

includes:
  # fe-local: ./frontend/Taskfile.local.yml
  fe-prod: ./frontend/Taskfile.prod.yml
  # be-local: ./infra/Taskfile.local.yml
  be-prod: ./infra/Taskfile.prod.yml

tasks:
  fe-build-and-deploy:
    desc: Build and deploy the frontend
    cmds:
      - task: fe-prod:build
      - task: fe-prod:deploy

  be-validate-and-deploy:
    desc: Validate and deploy the backend
    cmds:
      - task: be-prod:validate
      - task: be-prod:deploy