version: 3

tasks:
  start:
    desc: "Start the local API"
    cmds:
      - nohup sh -c 'sam local start-api -t infra/template.yaml & echo $! > .sam.pid' > sam.log 2>&1 &
    silent: true

  stop:
    desc: "Stop the local API"
    cmds:
      - echo "Stopping local API..."
      - kill $(cat .sam.pid)
      - rm sam.log || true
      - rm .sam.pid || true
    silent: true



