AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  eks-versions-dashboard

  Sample SAM Template for eks-versions-dashboard

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 20
    LoggingConfig:
      LogFormat: JSON
      ApplicationLogLevel: INFO
      SystemLogLevel: WARN


Resources:
  EKSVersionsDashboardApi:
    Type: AWS::Serverless::Api # More info about API Resource:
    Properties:
      StageName: Prod
      # EndpointConfiguration: REGIONAL
      Cors:
        AllowMethods: "'OPTIONS,GET'"
        AllowHeaders: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
        AllowOrigin: "'*'"
        MaxAge: 3000
        StatusCode: 200 


  EKSVersionsDashboardBackend:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: backend/
      Handler: app.lambda_handler
      Runtime: python3.13
      Architectures:
      - x86_64
      Policies:
        - AWSLambdaBasicExecutionRole
        - PowerUserAccess
      Events:
        EKSVersionsDashboardApi:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /api/eks/clusters
            Method: GET
            RestApiId: !Ref EKSVersionsDashboardApi
            Auth:
              ApiKeyRequired: false

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  EKSVersionsDashboardApi:
    Description: API Gateway endpoint URL for Prod stage for Hello World function
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  EKSVersionsDashboardBackend:
    Description: Hello World Lambda Function ARN
    Value: !GetAtt EKSVersionsDashboardBackend.Arn
  EKSVersionsDashboardBackendIamRole:
    Description: Implicit IAM Role created for Hello World function
    Value: !GetAtt EKSVersionsDashboardBackendRole.Arn
